version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI_VIPER_CLIENT=121713273193.dkr.ecr.eu-west-1.amazonaws.com/viper_client
      - REPOSITORY_URI_VIPER_DUMMY=121713273193.dkr.ecr.eu-west-1.amazonaws.com/viper_dummy_api
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image viper client...
      - docker build -t $REPOSITORY_URI_VIPER_DUMMY:latest .
      - docker tag $REPOSITORY_URI_VIPER_DUMMY:latest $REPOSITORY_URI_VIPER_DUMMY:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI_VIPER_DUMMY:latest
      - docker push $REPOSITORY_URI_VIPER_DUMMY:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"viper_client","imageUri":"%s"},{"name":"viper_dummy_api","imageUri":"%s"}]' $REPOSITORY_URI_VIPER_CLIENT:latest $REPOSITORY_URI_VIPER_DUMMY:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json