import { WordPressPostModule } from "./wordpress-post-module";
import * as uuid from "uuid";
import { ApiModelProperty } from "@nestjs/swagger";
import { buttonCTA } from "./button-cta";
import { ItemOverviewCard } from "./item-overview-card";

export class ItemOverviewModule extends WordPressPostModule {
  @ApiModelProperty({ type: [ItemOverviewCard] })
  public cards: ItemOverviewCard[];
}

export const generateDummyItemOverviewModule = (): ItemOverviewModule => {
  return {
    cards: [
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },

      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      },
      {
        buttonText: "Lees meer",
        category: "Recept",
        leftItemIcon: "",
        leftItemText: "left item",
        picture: "https://s3-eu-west-1.amazonaws.com/viper-development-images/Terrasana/image-featured.1ebed0b8.jpg",
        rightItemIcon: "",
        rightItemText: "right item",
        title: "Title 1",
        URL: "/",
        id: uuid(),
        name: "ItemOverviewCard",
        bottomMargin: "0px",
        topMargin: "0px"
      }
    ],
    id: uuid(),
    name: "ItemOverviewCard",
    bottomMargin: "0px",
    topMargin: "0px"
  };
};
